### ISSUE TITLE
Main window only draggable

### ISSUE THREAD

**Issue by krysanto** [aichingm/spg_dp#12]
Main Window is only draggable.
Cant set any points or pathpoints

**Comment by aichingm** [comment]
Please provide more information! 
* OS
* Browser + version
* spg_dp version (commit hash)
* javascript console output

...

**Comment by krysanto** [comment]
-Windows
-Firefox v38.0.1 / Chrome v43.0.2357.81 m
-master (e4bea7710274851182a18630e8eef31a1eccc53d)
-Object { originalEvent: keypress, type: "keypress", isDefaultPrevented: Z(), timeStamp: 12074680, jQuery21307060449010341379: true, keyCode: 0, key: "K", charCode: 75, char: undefined, which: 75, 14

**Comment by krysanto** [comment]
Fixed
